import { TableItemProps as TableItemData } from "~/components/timetable/TableItem";

type Data = {
  out: {
    day1: TableItemData[];
    day2: TableItemData[];
  };
  in: {
    day1: TableItemData[];
    day2: TableItemData[];
  };
};

// スタート時刻
// out: 11:00
// in:  09:00
const timetableData: Data = {
  // スタート時刻は11:00
  out: {
    day1: [
      {
        eventTitle: "クイズ大会予選",
        description: "",
        start: "11:00",
        end: "12:00",
        time: 6,
        isBlank: false,
      },
      {
        eventTitle: "のど自慢",
        description: "",
        start: "12:00",
        end: "13:00",
        time: 6,
        isBlank: false,
      },
      {
        eventTitle: "吹奏楽コンサート",
        description: "",
        start: "13:00",
        end: "13:40",
        time: 4,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "クイズ大会決勝",
        description: "",
        start: "13:50",
        end: "15:00",
        time: 7,
        isBlank: false,
      },
      {
        eventTitle: "ビンゴ大会",
        description: "",
        start: "15:00",
        end: "16:00",
        time: 6,
        isBlank: false,
      },
    ],
    day2: [
      {
        eventTitle: "コスプレショー",
        description: "",
        start: "11:00",
        end: "12:00",
        time: 6,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 6,
        isBlank: true,
      },
      {
        eventTitle: "高専生の主張",
        description: "",
        start: "13:00",
        end: "13:30",
        time: 3,
        isBlank: false,
      },
      {
        eventTitle: "秘技披露",
        description: "",
        start: "13:30",
        end: "14:40",
        time: 7,
        isBlank: false,
      },
      {
        eventTitle: "クラス対抗ビンゴ大会",
        description: "",
        start: "14:40",
        end: "16:00",
        time: 8,
        isBlank: false,
      },
    ],
  },
  // スタート時刻は9:00
  in: {
    day1: [
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 6,
        isBlank: true,
      },
      {
        eventTitle: "mi media maranja",
        description: "",
        start: "10:00",
        end: "10:20",
        time: 2,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "ジェリコ",
        description: "",
        start: "10:30",
        end: "10:50",
        time: 2,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "ガサ入れプランクトン",
        description: "",
        start: "11:00",
        end: "11:20",
        time: 2,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "Crux.wav",
        description: "",
        start: "11:30",
        end: "11:50",
        time: 2,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 4,
        isBlank: true,
      },
      {
        eventTitle: "デジタルアーツ同好会",
        description: "",
        start: "12:30",
        end: "13:00",
        time: 3,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "ダンス同好会",
        description: "",
        start: "13:10",
        end: "13:30",
        time: 2,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "酒井晴渚",
        description: "",
        start: "13:40",
        end: "13:45",
        time: 0.5,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 0.5,
        isBlank: true,
      },
      {
        eventTitle: "ふかづめ",
        description: "",
        start: "13:50",
        end: "14:05",
        time: 1.5,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "Tusq",
        description: "",
        start: "14:15",
        end: "14:40",
        time: 2.5,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "山本",
        description: "",
        start: "14:50",
        end: "15:20",
        time: 3,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "OHMI",
        description: "",
        start: "15:30",
        end: "15:50",
        time: 2,
        isBlank: false,
      },
    ],
    day2: [
      {
        eventTitle: "ダンス同好会",
        description: "",
        start: "9:00",
        end: "9:20",
        time: 2,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "OHMI",
        description: "",
        start: "9:30",
        end: "9:50",
        time: 2,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "山本燎哉",
        description: "",
        start: "10:00",
        end: "10:30",
        time: 3,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "Tusq",
        description: "",
        start: "10:40",
        end: "11:05",
        time: 2.5,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "ふかづめ",
        description: "",
        start: "11:15",
        end: "11:30",
        time: 1.5,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 3,
        isBlank: true,
      },
      {
        eventTitle: "ガサ入れプランクトン",
        description: "",
        start: "12:00",
        end: "12:20",
        time: 2,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "Crux.wav",
        description: "",
        start: "12:30",
        end: "12:50",
        time: 2,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
      {
        eventTitle: "リサイクル",
        description: "",
        start: "13:00",
        end: "13:20",
        time: 2,
        isBlank: false,
      },
      {
        eventTitle: "",
        description: "",
        start: "",
        end: "",
        time: 1,
        isBlank: true,
      },
    ],
  },
};

export default timetableData;
