name: Format
on: [push, pull_request]

env:
  HUSKY: 0
  node-version: lts/*

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Format
        run: yarn run format:check
